# Generated by Django 5.2.1 on 2025-06-10 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('panel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hdmi_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('usb_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('refresh_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('energy_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('speaker_type', models.CharField(blank=True, choices=[('Bluetooth', 'Bluetooth'), ('Wired', 'Wired')], max_length=50, null=True)),
                ('connectivity', models.CharField(blank=True, choices=[('Bluetooth', 'Bluetooth'), ('AUX', 'AUX'), ('USB', 'USB'), ('Wi-Fi', 'Wi-Fi')], max_length=50, null=True)),
                ('power_source', models.CharField(blank=True, choices=[('Battery', 'Battery'), ('Wired', 'Wired')], max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Capacity in cubic feet', max_digits=5, null=True)),
            ],
            options={
                'db_table': 'product_types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dynamic_properties', models.JSONField(blank=True, help_text="Store custom fields for each product type. For example, a TV may have keys like 'screen_size', 'resolution', etc., while a Speaker might have 'speaker_type' or 'connectivity'.", null=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_type')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
